// Package mcpconfig materializes the umbrella-root .mcp.json from manifest
// services of kind "mcp". Only locally available connection data is used: an
// inline manifest connection block or a checked-in server.json descriptor.
// Nothing is ever fetched, and secret values never appear — env values pass
// through as ${VAR}-style placeholders or references.
package mcpconfig

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fluxinc/my-cli/internal/manifest"
)

const (
	targetFile = ".mcp.json"
	// sidecarFile remembers the last generated .mcp.json content so Ensure can
	// tell its own output from a hand-written file it must not clobber.
	sidecarFile = "mcp.json"
)

// Result describes one Ensure outcome.
type Result struct {
	TargetPath string `json:"target_path"`
	Status     string `json:"status"` // created | updated | ok | skipped | blocked
	Message    string `json:"message,omitempty"`
}

type serverEntry struct {
	Type    string            `json:"type,omitempty"`
	Command string            `json:"command,omitempty"`
	Args    []string          `json:"args,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
	URL     string            `json:"url,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
}

// Ensure writes <root>/.mcp.json for every materializable MCP service. A
// service materializes from its inline connection block, or, failing that,
// from a manifest-relative server.json descriptor. Files Ensure did not
// generate are never overwritten unless force is set.
func Ensure(root, manifestRoot string, services []manifest.Service, force bool) (Result, error) {
	target := filepath.Join(root, targetFile)
	res := Result{TargetPath: target}

	entries := map[string]serverEntry{}
	for _, service := range services {
		if service.Kind != "mcp" {
			continue
		}
		entry, ok, err := entryForService(manifestRoot, service)
		if err != nil {
			return res, err
		}
		if ok {
			entries[service.ID] = entry
		}
	}

	existing, err := os.ReadFile(target)
	exists := err == nil
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return res, err
	}

	if len(entries) == 0 && !exists {
		res.Status = "skipped"
		res.Message = "no MCP services with local connection data"
		return res, nil
	}

	desired, err := render(entries)
	if err != nil {
		return res, err
	}

	sidecar, err := lastGenerated(root)
	if err != nil {
		return res, err
	}

	switch {
	case exists && bytes.Equal(existing, desired):
		res.Status = "ok"
		return res, rememberGenerated(root, desired)
	case exists && !bytes.Equal(existing, sidecar) && !force:
		res.Status = "blocked"
		res.Message = fmt.Sprintf("%s exists and was not generated by my; merge the manifest services manually or re-run with --force", target)
		return res, nil
	}

	if err := os.WriteFile(target, desired, 0o644); err != nil {
		return res, err
	}
	if err := rememberGenerated(root, desired); err != nil {
		return res, err
	}
	if exists {
		res.Status = "updated"
	} else {
		res.Status = "created"
	}
	return res, nil
}

func entryForService(manifestRoot string, service manifest.Service) (serverEntry, bool, error) {
	if !service.Connection.IsZero() {
		return serverEntry{
			Type:    service.Connection.Type,
			Command: service.Connection.Command,
			Args:    service.Connection.Args,
			Env:     service.Connection.Env,
			URL:     service.Connection.URL,
			Headers: service.Connection.Headers,
		}, true, nil
	}
	if service.DescribeRef == "" || isURL(service.DescribeRef) {
		return serverEntry{}, false, nil
	}
	path := filepath.Join(manifestRoot, filepath.FromSlash(service.DescribeRef))
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return serverEntry{}, false, nil
	}
	if err != nil {
		return serverEntry{}, false, err
	}
	var entry serverEntry
	if err := json.Unmarshal(data, &entry); err != nil {
		return serverEntry{}, false, fmt.Errorf("service %q descriptor %s: invalid JSON: %w", service.ID, path, err)
	}
	if entry.Command == "" && entry.URL == "" {
		return serverEntry{}, false, nil
	}
	return entry, true, nil
}

func isURL(value string) bool {
	return strings.HasPrefix(value, "http://") || strings.HasPrefix(value, "https://")
}

func render(entries map[string]serverEntry) ([]byte, error) {
	doc := struct {
		Servers map[string]serverEntry `json:"mcpServers"`
	}{Servers: entries}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func sidecarPath(root string) string {
	return filepath.Join(root, ".my-cli", "derived", sidecarFile)
}

func lastGenerated(root string) ([]byte, error) {
	data, err := os.ReadFile(sidecarPath(root))
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	return data, err
}

func rememberGenerated(root string, content []byte) error {
	path := sidecarPath(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}
